gordonwatts/CalRatioTrainer

- .vscode/settings.json
- cal_ratio_trainer/config.py
- cal_ratio_trainer/trainer.py
- cal_ratio_trainer/utils.py
- tests/test_utils.py
* Fixes #23: add all simple trianing parameters to the command line.
* Fixes #22: Add a pring settings option to print out configuration for the run, but not actually run.
> Improving the Command Line for training parameters

- cal_ratio_trainer/config.py
- cal_ratio_trainer/default_training_config.yaml
- cal_ratio_trainer/training/runner_utils.py
`learning_rate` wasn't used anywhere, but was in our parameter list. This gets rid of it in the source code.
Fixes #25
> Remove the parameter `learning_rate`

- cal_ratio_trainer/config.py
- tests/test_config.py
- tests/test_with_file_url.yaml
* Shift from AnyUrl to using a string for the URL. AnyURL turns out to not know about a url that is complete when it comes to a `file:` protocal!
* This also also has the side effect of fixing #43
Fixes #44, #43
> Fix up file://./ bug

- cal_ratio_trainer/config.py
- cal_ratio_trainer/convert/convert_divert.py
- cal_ratio_trainer/trainer.py
This feature is only accessible via `ymal` configuration:
* If for a file or group of files an `output_dir` string is specified, the output file will be written into that directory.
Fixes #72
> Basic build command boilerplate (#69)

- .gitignore
- cal_ratio_trainer/convert/convert_divert.py
- tests/convert/test_convert_divert.py
* If the output pkl file already exists, then skip the training. Issue a logging message.
Fixes #78
> Do not convert a file that already exists

- README.md
- cal_ratio_trainer/config.py
- cal_ratio_trainer/convert/convert_divert.py
- cal_ratio_trainer/trainer.py
* Any `Exception` thrown during a file processing is caught and reported
* The system will move onto the next file.
* Documentation was updated to make it clear that the person needs to look carefully at the output to catch what is going on.
Fixes #82
> Files with bad permissions should be ignored safely. Actually, any recoverable error should be ignored.

- cal_ratio_trainer/config.py
- cal_ratio_trainer/default_build_main_training_config.yaml
* Change default in the config file
* Add some minor documentation updates to make it clear what it gets used for
Fixes #89
> Default max value of jet pT should be 500 GeV, not 400 GeV

- cal_ratio_trainer/build/build_main.py
- cal_ratio_trainer/config.py
- tests/build_training/test_build_main.py
* Allow filtering at the event level
* Use `pandas.DataFrame.query` with the expression comming from the `config` object.
Fixes #94
> Allow filtering at the event level

- .vscode/settings.json
- cal_ratio_trainer/build/build_main.py
This was a first step in trying to address how much memory is getting used when the training file is built. We keep running out.
* Added some logging information
* Do preprocessing on much smaller chunks of data - hopefully this will improve memory and paging issues.
Unfortunately, more clever work is going to need to be done in order to get around the memory problems.
Fixes #96
> Reorg how the data is getting put together to be built to make it more efficient

- .vscode/settings.json
- cal_ratio_trainer/build/build_main.py
- cal_ratio_trainer/common/fileio.py
- tests/build_training/test_build_main.py
The `SetViewCopy` warning from `pandas` is caused by updating a column - and not doing it in place. One needs to use `df.loc[:, "column"] = xxx` rather than `df["column"]`. This is to remove all these warnings generated by `pandas` during the `build` process.
* Cleaning this up made the `build` proecss x2 more efficient in memory usage.
* Removed some calculation columns that were just carried along for the rid, but never used.
* Improevd logging so we could better understand how far things were getting before running out of memory.
Fixes #103
> `pandas` is giving lots of vew/copy setting warnings.

- cal_ratio_trainer/build/build_main.py
- tests/build_training/test_build_main.py
Some upstream files are showing up "damaged" - lets put in a quick fix for now, and then fix things upstream later.
* Rename, on the fly, `mS` and `mH` to `llp_mS` and `llp_mH`.
Fixes #114
> Test to check for proper column names

- .vscode/settings.json
- cal_ratio_trainer/config.py
- cal_ratio_trainer/convert/convert_divert.py
- cal_ratio_trainer/default_divert_config.yaml
- tests/convert/test_convert_divert.py
- tests/data/sample_divert_convert.yaml
- tests/test_config.py
* Make sure to write `llp_mS` rather than `mS`. Fixes #106
* Remove the `is_HTL_BIB` column requirement. Fixes #81
* Make sure to set types to float64 (like llp_mS, etc.). Fixes #100
* Associate masses with each input file set. Fixes #118
> Epic PR to fix small bugs in how we do the conversion

- cal_ratio_trainer/build/build_main.py
- cal_ratio_trainer/config.py
- tests/build_training/test_build_main.py
Add a list of branches - if we spot them, we drop them.
* Main commit was done into `main` directly by accident. Ops.
* Added some logging to indicate when this was triggered.
* Make sure defaults are all `None` - or the logic won't copy them over.
Fixes #122
> During build, have a list of branches we can drop 

- cal_ratio_trainer/build/build_main.py
- tests/build_training/test_build_main.py
- tests/convert/test_convert_divert.py
* Rescale the `clust_pt_XXX` by the total cluster `p_T`.
Noticed that the sorting seems to be backwards compared to what we might expect - putting the lowest $p_T$ first rather than last in the list. Need to check that is what we want (or not).
Fixes #125
> Test cluster pt 0 is written correctly

- cal_ratio_trainer/convert/convert_divert.py
- tests/convert/test_convert_divert.py
* If there are more than 20 tracks or more than 30 msegs or clusters, make sure to truncate.
Fixes #138
> Protect against too many tracks, clusters, msegs

- .github/workflows/ci.yaml
* Implemented using the `actiosn/cache@v3`
While this looks like it is working, we can't save the cache until the CI succeeds more often. So we won't declare #148 fixed just yet.
> Cache for pip-install in the github CI

- cal_ratio_trainer/build/build_main.py
- tests/build_training/test_build_main.py
When still running the converter sometimes the directories contain lock files - and that was causing a crash. This only looks for `pkl` files in the directories.
Fixes #158
> Make sure to only fetch pickle files for building

- cal_ratio_trainer/convert/convert_divert.py
- tests/convert/test_convert_divert.py
We were only looking at positive Lz distributions, which was killing the signal at negative eta distributions.
Fixes #161
> Use positive and negative Lz distributions

- cal_ratio_trainer/build/build_main.py
Comparisons of our data files and Felix's show a real difference in the shape and value of `cluster_pt`.
Fixes #162
> Cluster pT should not be rescaled by fractions, but by a constant number instead.

- cal_ratio_trainer/reporting/training_file.py
We were making an assumption that any event with a non-zero $m_S$ or $m_H$ was signal. Turns out not to be the case - Felix's old trianing files seem to have assigned $m_H$ and $m_S$ values to the jet data!
This first filters on the `label` before looking at `llp_mS` or `llp_mH`.
Fixes #172
> Only plot signal files that are signal file events

- cal_ratio_trainer/reporting/training_file.py
* Changed the over-view plots (those that appear at the top level in the report) to use `mcEventWeight`
* Did not change the "all plots" - where a plot for *everything* is made - to use event weights.
Fixes #49
> Report plots should use weights

- .gitignore
- cal_ratio_trainer/build/build_main.py
- cal_ratio_trainer/config.py
- cal_ratio_trainer/convert/convert_divert.py
- cal_ratio_trainer/trainer.py
* Added better defaults to the `convert divertanalysis` command so that it can easily be run on a divert analysis root file.
* `asserts` that are often badly supplied user data need some sort of error message to help the user
* `logging.debug` statements added at several places to help with tracking down problems.
Fixes #210
> Make Failures More Obvious during Running

- cal_ratio_trainer/trainer.py
model-dump only requires `<training-name>/<number>`, instead of `<training-name>/<number>/<epoch>`. Modified -h output to reflect this.
> changed instructions in model-dump to match reality
