gordonwatts/CalRatioTrainer

.gitignore
cal_ratio_trainer/training/deepJet_train_keras.py

* Optimizers can have their learning rate re-set. No need to keep re-creating them.
Fixes #3

Don't keep re-creating the optimizers

---

cal_ratio_trainer/config.py
tests/test_config.py
tests/test_config.yaml

* Fixing a bug because... we didn't have testing!
Fixes #7

Loading a new config only replaces the non-None values

---

.vscode/settings.json
cal_ratio_trainer/training/training_utils.py

* Refactor the padding code
* Found one bug in variable name propagation.
Partially addressing #9

With large datasets can't validate

---

cal_ratio_trainer/training/training_utils.py
tests/test_training_utils.py

* Added several tests
* Fixed one bug b.c. we weren't calculating the padding right
Working on #9

More robust array padding

---

cal_ratio_trainer/training/deepJet_train_keras.py
cal_ratio_trainer/training/evaluate_training.py
cal_ratio_trainer/training/training_utils.py

This is addressing #20
* Remove all code that adjusts the learning rate
* Remove all the plotting code that worked with the LR
* Remove some old commented out code
This makes significant improvements to the spiky nature of the learning rate.

Turn off learning rate adjustments as experiment

---

cal_ratio_trainer/training/utils.py
tests/training/test_utils.py

Filter directories before deciding to convert them to integers
Fixes #33

Deal with non-integer directories and files in a training

---

cal_ratio_trainer/reporting/md_report.py
cal_ratio_trainer/reporting/training_file.py

Most browsers can't deal with all the figures.
* plots that were thumbnais in the final column table are now just links.
Fixes #40

Output table plots as links

---

.vscode/launch.json
cal_ratio_trainer/common/evaulation.py
cal_ratio_trainer/config.py
cal_ratio_trainer/default_analyze_config.yaml
cal_ratio_trainer/reporting/analyze.py
cal_ratio_trainer/reporting/evaluation_utils.py
cal_ratio_trainer/reporting/md_report.py
cal_ratio_trainer/trainer.py
cal_ratio_trainer/training/deepJet_train_keras.py
cal_ratio_trainer/training/evaluate_training.py
cal_ratio_trainer/training/utils.py
cal_ratio_trainer/utils.py
tests/test_utils.py
tests/training/test_utils.py

Generate a report that looks for the "best" epochs in a collection of trainings.
* Added analyze command
* Analyze command look through tape of several runs and picks out the "best" one
* Dumps plots and tables of data
* Evaluates on test data the pass rates for the various mass combinations, and the ROC
* Refactor as more code is needed outside the training code to support all this.
* Fix up how we print out the master AUC for everything - do it not just for one mass, but for everything.
* Better dealing with funny characters in figures that are being written out.
Fixes #50, #54

Add analyze command

---

.gitignore
.gitmodules
README.md
cal_ratio_trainer/config.py
cal_ratio_trainer/convert/convert_json.py
cal_ratio_trainer/default_convert_config.yaml
cal_ratio_trainer/trainer.py

The C++ DiVertAnalysis uses the keras models encoded as `json`.
* Added the `convert` command that will convert a model/run/epoch to `json` for `fdeep`
* Uses the `fdeep` package to run the conversion
* Includes the `fdeep` package as a sub-module in the `convert` directory.
Fixes #46

Add convert command to output json

---

.gitignore
cal_ratio_trainer/build/build_main.py
cal_ratio_trainer/config.py
cal_ratio_trainer/default_build_main_training_config.yaml
cal_ratio_trainer/trainer.py

Build a main training source file:
* Uses a list of input files and # of events
* Runs the final reweighting and phi subtractions
Fixes #68

Basic build command boilerplate

---

.gitignore
.vscode/settings.json
README.md
pyproject.toml
tests/convert/test_convert_divert.py

* Add a test that runs on 100 events of signal
* Added instructions and packages to easily profile tests.
Fixes #80

Add test for signal and determine speed

---

cal_ratio_trainer/build/build_main.py
tests/build_training/test_build_main.py

Tricky way path handles `glob`. It is rather specific, but flexible, and we weren't really "doing it" right. This will strip off all the wildcard parts of the expression and just glob those. Or no glob at all if it isn't needed.
Fixes #92

Make sure `glob` works for nested directories in the build

---

cal_ratio_trainer/build/build_main.py
pyproject.toml

* Rewrite the `build` portion to use `dask.DataFrame`, the `dask` implementation of the  `pandas` DataFrame
Code got significantly shorter (and mostly easier to use). And was able to complete without memory issues. Amazing!
Fixes #105

First use of DASK to process the dataframes that come in.

---

cal_ratio_trainer/build/build_main.py
tests/build_training/test_build_main.py

Prints out an error message
Fixes #110

Fail nicely when of files match the list of files for building

---

README.md
cal_ratio_trainer/common/file_lock.py
cal_ratio_trainer/convert/convert_divert.py
cal_ratio_trainer/trainer.py
tests/common/test_file_lock.py
tests/convert/test_convert_divert.py

* Add a nice file locking object that was suggested by AI
* Make sure to obey the lock when running the conversion.
* update notes so this is known
Fixes #120

Allow multiple copies of the `convert divertanalysis` to run simultaneously

---

.vscode/settings.json
cal_ratio_trainer/convert/convert_divert.py
tests/convert/test_convert_divert.py

* Update the `llp` cuts to include the endcap.
Fixes #124

Signal should be kept in endcap

---

cal_ratio_trainer/convert/resample.py
cal_ratio_trainer/trainer.py

* Adds the `resample` command that takes a `pkl` input and output file and fraction - and generates a smaller file on demand.
Working towards #134

Adds a resampling command to generate smaller training files.

---

cal_ratio_trainer/config.py
cal_ratio_trainer/convert/convert_divert.py
cal_ratio_trainer/default_build_main_training_config.yaml
cal_ratio_trainer/default_divert_config.yaml
tests/convert/test_convert_divert.py

* Added min and max jet pt cuts for the conversion process
* Change default rescaling jet pt number to 0.0 rather than 40.0
The paper and code differ on how cluster pt is scaled 
Fixes #132

Add min and max jet pt cuts as configurable.

---

cal_ratio_trainer/build/build_main.py
cal_ratio_trainer/convert/convert_divert.py

* If no data in file, then skip out early
* Minor logging update
Fixes #139

Remove bogus error because we didn't check for empty file

---

.github/workflows/ci.yaml
cal_ratio_trainer/common/trained_model.py
pyproject.toml

* Add GitHub CI test workflow
* Add sub-module `__init__,py` files
* Make sure data files are included in the distribution
Fixes #135

Adds a github CI test workflow

---

cal_ratio_trainer/build/build_main.py
cal_ratio_trainer/config.py
cal_ratio_trainer/convert/convert_divert.py
cal_ratio_trainer/default_build_main_training_config.yaml
cal_ratio_trainer/default_divert_config.yaml
tests/build_training/test_build_main.py

* Normalize spelling of `pT` to `pt` in both build and convert
Fixes #146

Fix up capitalization of pT vs pt

---

cal_ratio_trainer/convert/resample.py

* Added code to do it by label
Fixes #154

Resample by label to keep fractions even

---

cal_ratio_trainer/build/build_main.py
tests/build_training/test_build_main.py

* Track and cluster delta phi improved to wrap phi properly so we don't have any "bumps" out around 2$\pi$.
Fixes #165

Fix phi wrap bug for clusters and tracks

---

cal_ratio_trainer/default_reporting_config.yaml

* More complete set of plots for fast comparisons.
Fixes #163

Add extra default plots for standard file plotting

---

cal_ratio_trainer/common/fileio.py

Will allow for better comparisons with plots.
Fixes #171

Remove `aux_` from variable names

---

cal_ratio_trainer/common/fileio.py
tests/common/test_fileio.py

* Add a direct simple test for `load_dataset`
* Do all dataframe manipulations `inplace` that we can easily.
Fixes #176

Be more careful of memory in `load_dataset`

---

README.md
cal_ratio_trainer/common/column_names.py
cal_ratio_trainer/common/evaluation.py
cal_ratio_trainer/convert/convert_divert.py
cal_ratio_trainer/default_reporting_config.yaml
cal_ratio_trainer/reporting/analyze.py
cal_ratio_trainer/reporting/training_file.py
cal_ratio_trainer/training/evaluate_training.py
cal_ratio_trainer/training/utils.py

* Move from magic numbers for the labels to an actual `enum`
* This required changes through out all phases of the code. Touched a lot of files!
* Make QCD to label 0 and Signal be label 1.
Fixes #179

QCD is label 0, Signal is label 1

---

cal_ratio_trainer/convert/convert_divert.py
tests/convert/test_convert_divert.py

* Fix up some newly flagged type errors
* Shift the cluster eta/pt to be relative to the the highest pt cluster.
Fixes #190

Fix up some new type errors

---

README.md

Changed cloning instructions to include ` --recurse-submodules` tag.

changed ReadMe to have submodule support

---

cal_ratio_trainer/convert/convert_divert.py

Added an additional step to the divert_convert.py script that will convert root files to parquet files and write the parquet file out as a step in the training process. Parquet files are much faster to read in than root files, so this conversion is useful if we need to convert the same file multiple times.

Adding parquet conversion

---

.github/workflows/ci.yaml
cal_ratio_trainer/config.py
cal_ratio_trainer/convert/convert_divert.py
cal_ratio_trainer/trainer.py
cal_ratio_trainer/utils.py
pyproject.toml

Modified high and low mass flags. Calling --include_high_mass will run training with only high mass samples and no low mass samples, and vice versa for --include_low_mass flag. Including both flags or neither flags will run training with both high and low mass samples.
(Also formatted it correctly this time).

Modified include_low_mass and include_high_mass flags

---

cal_ratio_trainer/training/evaluate_training.py

Added a y axis for the linear prediction histograms in order to make it easier to compare different trainings.

Set y axis in linear histograms
